#!/bin/sh

package=github.com/mikelangelo-project/capstan
version=$(scripts/version)

OLDIFS=$IFS
IFS=' '; set -- $(go version)
IFS='.'; set -- $3
IFS=$OLDIFS
if [ $2 -gt 4 ]; then
    link_operator="="
else
    link_operator=" "
fi

go get $package
go build -a -ldflags "-X main.VERSION$link_operator'$version' -w -s" -tags netgo $package
go install $package
